development:
  adapter: postgresql
  database: igf_development
  host: localhost
  socket: /tmp/mysql.sock
  encoding: UTF8
  min_messages: WARNING
  pool: 25
  
test:
  adapter: postgresql
  database: igf_test
  host: localhost
  socket: /tmp/mysql.sock
  encoding: UTF8
  min_messages: WARNING
  pool: 25